---
title: "INTERACTIVE EFFECTS OF MULTIPLE STRESSORS ACROSS BULL KELP’S (NEREOCYSTIS LUETKEANA, PHAEOPHYCEAE) LIFE-HISTORY"
subtitle: "Loading packages, data, and themes and creating data subsets"
author: "Shirah Strock"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    number_section: false
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    collapsed: true
    number_section: false
    theme: united
---

# Importing and preparing data

## Loading packages

```{r}
library(tidyr)
library(tidyverse)
library(glmmTMB)
library(nlme)
library(factoextra)
library(multcomp)
library(devtools)
library(ggbiplot)
library(ggpubr)
library(lme4)
library(lmerTest)
library(tidymodels)
library(performance)
library(DHARMa)
library(tweedie)
library(ggplot2)
library(ggeffects)
library(emmeans)
library(car)
library(FSA)
library(mgcv)
library(multcompView)
library(vegan)
library(ggrepel)
library(ggcorrplot)
library(dplyr)
library(DescTools)
library(effectsize)
library(esc)
library(esvis)
library(gridExtra)
library(patchwork)
library(cowplot)
library(ggpattern)
library(pairwiseAdonis)
library(here)
```

## Creating theme for plots 

```{r}
my_theme <-theme (panel.border = element_rect(colour = "black",
                                              fill = NA,
                                              linewidth = 1))+
  theme_bw(base_size = 14, base_family = "")+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        panel.background = element_blank())+
  theme(axis.text = element_text(color = "black"))
```

## Loading and mutating data

```{r}
#read csv from the raw data file using the here function
data <- read_csv(file = paste0(here(),
                                  '/raw_data/experiment_data_final.csv'))

#mutate for correct data type for columns
data <- mutate(data, analysis_date = as.Date(analysis_date),
               treatment_num = as.factor(treatment_num),
               replicate_num = as.factor(replicate_num),
               salinity_treat = as.factor(salinity_treat),
               temp_treat = as.factor(temp_treat),
               gam_number = as.character(gam_number),
               sporophyte_num = as.character(sporophyte_num),
               blade_num = as.character(blade_num),
               cross_sec_num = as.character(cross_sec_num),
               cell_num = as.character(cell_num),
               cell_type = as.factor(cell_type),
               view = as.character(view),
               blade_wet_mass = as.numeric(blade_wet_mass))


#reading data file for macroscopic sporophyte counts 
macro_counts <- read_csv(file = paste0(here(),
                                       '/raw_data/exp_macro_sporo_count_data.csv'))

macro_counts <- mutate(macro_counts, 
                       treatment = as.factor(treatment),
                       replicate = as.factor(replicate),
                       salinity_treat = as.factor(salinity_treat),
                       temp_treat = as.factor(temp_treat))
```

## Creating subsets and data transformations

```{r}
spores <- subset(data, days_post_release < 9)

gam <- subset(data, days_post_release<72)


gams <- subset(gam, days_post_release > 2)



day_9 <- subset(data, days_post_release == 9)
day_15 <- subset(data, days_post_release == 15)
day_22 <- subset(data, days_post_release == 22)
day_29 <- subset(data, days_post_release == 29)
day_36 <-subset(data, days_post_release == 36)
day_42 <- subset(data, days_post_release ==42)
day_72 <- subset(data, days_post_release == 72)
day_92 <- subset(data, days_post_release ==92)
day_99 <- subset(data, days_post_release == 99)
day_107 <- subset(data, days_post_release == 107)
day_255 <- subset(data, days_post_release == 255)



gam_info <- subset(gams, 
                   select = c(gam_count, 
                              gam_density, 
                              gam_percent_cover, 
                              gam_size_um2))

gam_t1 <- subset(gams, treatment_num == 1)
gam_t2 <- subset(gams, treatment_num == 2)
gam_t3 <- subset(gams, treatment_num == 3)
gam_t4 <- subset(gams, treatment_num == 4)


sp <- subset(data, days_post_release > 42)

micro_sporos <- subset(sp, days_post_release < 255)


micro_sporo_info <- subset(micro_sporos, 
                           select = c(gam_percent_cover,
                                      oogonia_density,
                                      sporophyte_density,
                                      sporophyte_percent_cover,
                                      sporophyte_size_um2))


day_255_cort<-subset(day_255, cell_type == "cortical")

day_255_epi<-subset(day_255, cell_type == "epidermal")

#transforming some data 
log_gam_den <- log10(gams$gam_density)
sqrt_gam_den<-sqrt(gams$gam_density)
log_gam_size<-log10(gams$gam_size_um2)


gams<-cbind(gams, log_gam_den)
gams<-cbind(gams, sqrt_gam_den)
gams<-cbind(gams, log_gam_size)


log_sporophyte_cover <- log(micro_sporos$sporophyte_percent_cover)
sqrt_sporophyte_cover <-sqrt(micro_sporos$sporophyte_percent_cover)

micro_sporos<- cbind(micro_sporos, log_sporophyte_cover)
micro_sporos<- cbind(micro_sporos, sqrt_sporophyte_cover)
```
