---
title: "INTERACTIVE EFFECTS OF MULTIPLE STRESSORS ACROSS BULL KELP’S (NEREOCYSTIS LUETKEANA, PHAEOPHYCEAE) LIFE-HISTORY"
subtitle: "Assessing Spore Settlement"
author: "Shirah Strock"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    number_section: false
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    collapsed: true
    number_section: false
    theme: united
---

# Assessing spore settlement

## Calculating mean spore settlement

```{r}
#mean and sd for spore settlement in each treatment 
spores %>%
  group_by(treatment_num) %>%
  summarise(mean_spore_setden = mean(settlement_density),
            sd_spore_setden = sd(settlement_density))

#overall mean spore settlement
mean(spores$settlement_density)
```

## Models

```{r}
#visualize raw spore data distribution
hist(spores$settlement_density) 
#View(spores)  


#ANOVA for spore settlement
spore_anova <- aov(settlement_density ~ treatment_num,
                   data = spores) 
summary(spore_anova) 
# F = 1.024, p = 0.403  

#Check ANOVA assumptions
qqnorm(residuals(spore_anova))
qqline(residuals(spore_anova), col = "red")
shapiro.test(residuals(spore_anova)) 
# p = 0.3162 - normality assumption met 

plot(spore_anova, which = 1) 

leveneTest(settlement_density ~ treatment_num, data = spores) 
#p=0.7972 - equal variance assumption met
```
