---
title: "INTERACTIVE EFFECTS OF MULTIPLE STRESSORS ACROSS BULL KELP’S (NEREOCYSTIS LUETKEANA, PHAEOPHYCEAE) LIFE-HISTORY"
subtitle: "Assessing oogonia density"
author: "Shirah Strock"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    number_section: false
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    collapsed: true
    number_section: false
    theme: united
---

# Assessing Oogonia Density

## Models

```{r}
#Oogonia density model
#viewing data distribtuion
hist(micro_sporos$oogonia_density)

#adjust data to account for zeros (this was the best fit for data)
micro_sporos$oogonia_density_adj <- micro_sporos$oogonia_density + 0.001

#Gamma glmm
oogonia_lm <- glmmTMB(oogonia_density_adj ~ salinity_treat * temp_treat +
                        (1|days_post_release) + (1|replicate_num),
                      family = Gamma(link = "log"),
                      data = micro_sporos)

summary(oogonia_lm)


table(micro_sporos$oogonia_density == 0, micro_sporos$salinity_treat, micro_sporos$temp_treat)







#assessing model fit using DHARMa
sim_reso <- simulateResiduals(fittedModel = oogonia_lm, plot = TRUE)


# Test for over/underdispersion
testDispersion(sim_reso)

# Test for outliers
testOutliers(sim_reso)

#Test model inflation due to zeros
testZeroInflation(sim_reso)

plotResiduals(sim_reso, form = fitted(oogonia_lm))
```

## Calculating estimated marginal means

```{r}
#calculate estimated marginal means based on Gamma model
emmo <- emmeans(oogonia_lm, ~ salinity_treat * temp_treat, 
                 type = "response") 

emmo_df <- as.data.frame(emmo)

# Pairwise comparisons with Tukey adjustment
pairwise_emmo <- contrast(emmo, method = "pairwise", adjust = "tukey")
summary(pairwise_emmo)

# Compact letter display for grouping
cld_letterso <- multcomp::cld(emmo, Letters = letters, adjust = "tukey")

# Convert to dataframe and merge
emmo_df <- as.data.frame(cld_letterso)
emmo_df

#removing spaces from the compact letter display
emmo_df$.group <- trimws(emmo_df$.group)

names(emmo_df)
```

## Visualizations

```{r}
emm_o <- ggplot(emmo_df, aes(x = salinity_treat, y = response, 
                     fill = temp_treat)) +
  geom_bar(stat = "identity", position = position_dodge(0.95)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),
                width = 0.1, position = position_dodge(0.95)) +
  geom_text(aes(label = .group, y = asymp.UCL + 200),
            position = position_dodge(0.95),
            color = "black") +
  scale_fill_manual(
    values = c("amb" = "darkgrey", "inc" = "#505050"),
    labels = c("amb" = "Ambient", "inc" = "Increased")) +
  scale_x_discrete(labels = c("amb" = "Ambient", "dec" = "Decreased")) +
  labs(x = "Salinity Treatment", 
       y = expression("Oogonia Density (oogonia·mm "^-2*")"),
       fill = "Temperature\nTreatment")+
  my_theme
emm_o

#plot with line showing theoretical addition response (Crain et al. 2008)
ggplot(emmo_df, aes(x = salinity_treat, y = response, 
                    fill = temp_treat)) +
  geom_bar(stat = "identity", position = position_dodge(0.95)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),
                width = 0.1, position = position_dodge(0.95)) +
  geom_text(aes(label = .group, y = asymp.UCL + 200),
            position = position_dodge(0.95),
            color = "black") +
  scale_fill_manual(
    values = c("amb" = "darkolivegreen1", "inc" = "darkolivegreen"),
    labels = c("amb" = "Ambient", "inc" = "Increased")) +
  scale_x_discrete(labels = c("amb" = "Ambient", "dec" = "Decreased")) +
  labs(x = "Salinity Treatment", 
       y = expression("Oogonia Density (oogonia·mm "^-2*")"),
       fill = "Temperature\nTreatment")+
  geom_segment(aes(x = 2, xend = 2.5, y = 2236.5452),
               linetype = "dashed",
               color = "black",
               linewidth =1 ) +
  my_theme



#saving the figure to the figure_outputs folder 
ggsave("figure3.jpg", plot = emm_o, width = 6, height = 7, 
       dpi = 300, units = "in",
       path = 'figure_outputs')

#save as pdf
ggsave("Figure_3.pdf", plot = emm_o, width = 6, height = 5, 
       dpi = 600, units = "in",
       path = 'figure_outputs')
```
