---
title: "INTERACTIVE EFFECTS OF MULTIPLE STRESSORS ACROSS BULL KELP’S (NEREOCYSTIS LUETKEANA, PHAEOPHYCEAE) LIFE-HISTORY"
subtitle: "Assessing macroscopic sporophyte counts and cell sizes"
author: "Shirah Strock"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    number_section: false
  html_document:
    df_print: paged
    toc: true
    toc_float: true
    collapsed: true
    number_section: false
    theme: united
---

# Assessing Macroscopic Sporophyte Counts 

## Model

```{r}
#view raw data distribution 
hist(macro_counts$total)

#negative binomial model for macroscopic kelp counts in each treatment
macro_counts_lm<-glmmTMB(total ~ salinity_treat * temp_treat + 
                           (1|days_post_release) + (1|replicate),
                         ziformula = ~1,
                         family = nbinom2,
                         data = macro_counts)
summary(macro_counts_lm)


#Assess model fit using DHARMa
sim_res_mac_count <- simulateResiduals(fittedModel = macro_counts_lm, 
                                       plot = TRUE)



# Test for over/underdispersion
testDispersion(sim_res_mac_count)

# Test for outliers
testOutliers(sim_res_mac_count)

# Test for zero-inflation
testZeroInflation(sim_res_mac_count)

plotResiduals(sim_res_mac_count, form = macro_counts$salinity_treat)
plotResiduals(sim_res_mac_count, form = macro_counts$temp_treat)


# Pairwise comparisons for salinity × temperature
emmeans(macro_counts_lm, pairwise ~ salinity_treat * temp_treat)
```

## Calculating estimated marginal means

```{r}
#calculating emmeans for macroscopic counts
macro_count_emm <- emmeans(macro_counts_lm, ~ salinity_treat * temp_treat, type = "response")

#pairwise comparisons
pairwise_emm_macro_count <- contrast(macro_count_emm, method = "pairwise", adjust = "tukey")
summary(pairwise_emm_macro_count)

#compact letter display
mac_count_cld_emm <- cld(macro_count_emm, Letters = letters, adjust = "sidak")
print(mac_count_cld_emm)

#removing the spaces in the compact letter display
mac_count_cld_emm$.group <- trimws(mac_count_cld_emm$.group)
```

## Visualizations

```{r}
mac_count_plot <- ggplot(mac_count_cld_emm, aes(x = salinity_treat, 
                              fill = temp_treat,
                              y = response, group = temp_treat)) +
  geom_bar(stat = "identity", position = position_dodge(0.95)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.08,
                position = position_dodge(0.95)) +
  geom_text(aes(label = .group, y = asymp.UCL + 3),color="black", 
            position = position_dodge(0.95)) +
  labs(x = "Salinity Treatment",
       y = "Macroscopic Sporophyte Count",
       fill = "Temperature") +
  scale_x_discrete(labels = c("Ambient","Decreased"))+
  scale_fill_manual(values = c("darkgrey","#505050"),
                      labels = c("Ambient","Increased"))+
  my_theme
mac_count_plot


#saving the figure to the figure_outputs folder 
ggsave("figure5.jpg", plot = mac_count_plot, width = 6, height = 7, 
       dpi = 300, units = "in",
       path = 'figure_outputs')

#save as pdf
ggsave("Figure_5.pdf", plot = mac_count_plot, width = 6, height = 5, 
       dpi = 600, units = "in",
       path = 'figure_outputs')



#plot with line showing additive response (Crain et al. 2008)
mac_count_plot2 <- ggplot(mac_count_cld_emm, aes(x = salinity_treat, 
                              fill = temp_treat,
                              y = response, group = temp_treat)) +
  geom_bar(stat = "identity", position = position_dodge(0.95)) +
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), width = 0.08,
                position = position_dodge(0.95)) +
  geom_text(aes(label = .group, y = asymp.UCL + 3),color="black", 
            position = position_dodge(0.95)) +
  labs(x = "Salinity Treatment",
       y = "Macroscopic Sporophyte Count",
       fill = "Temperature") +
  scale_x_discrete(labels = c("Ambient","Decreased"))+
  scale_fill_manual(values = c("darkolivegreen1","darkolivegreen"),
                    labels = c("Ambient","Increased"))+
  geom_segment(aes(x = 2, xend = 2.55, y = 0),
               linetype = "dashed",
               color = "black",
               linewidth = 1) +
  my_theme
mac_count_plot2

#saving the figure to the figure_outputs folder 
ggsave("mac_count_plot2.jpg", plot = mac_count_plot2, width = 6, height = 7, 
       dpi = 300, units = "in",
       path = 'figure_outputs')
```

# Assessing Macroscopic Sporophyte Cortical Cell Size

## Model

```{r}
#view raw data distribution
hist(day_255_cort$cell_area_um2)

#Gamma model
macrosporo_cort_lm<- glmmTMB(cell_area_um2 ~ salinity_treat + temp_treat +
                               (1|replicate_num) + (1|blade_num),
                             dispformula = ~ salinity_treat,
                             data = day_255_cort,
                             family = Gamma(link = "log"))
summary(macrosporo_cort_lm)


#tests model assumptions with DHARMa
sim_resmacro1 <- simulateResiduals(fittedModel = macrosporo_cort_lm, plot = TRUE)


# Test for over/underdispersion
testDispersion(sim_resmacro1)

# Test for outliers
testOutliers(sim_resmacro1)

# Tests for zero-inflation
testZeroInflation(sim_resmacro1)

plotResiduals(sim_resmacro1, form = day_255_cort$salinity_treat)
plotResiduals(sim_resmacro1, form = day_255_cort$temp_treat)

```

# Assessing Macroscopic Sporophyte Epidermal Cell Size

## Model

```{r}
#view raw data distribution 
hist(log(day_255_epi$cell_area_um2))

#GLMM log transfomred data
macrosporo_epi_lm<- glmmTMB(log(cell_area_um2) ~ salinity_treat + temp_treat +
                               (1|replicate_num) + (1|blade_num),
                            dispformula = ~ salinity_treat,
                             data = day_255_epi)
summary(macrosporo_epi_lm)


#check model assumptions using DHARMa
sim_resmacro2 <- simulateResiduals(fittedModel = macrosporo_epi_lm, plot = TRUE)


# Test for over/underdispersion
testDispersion(sim_resmacro2)

# Test for outliers
testOutliers(sim_resmacro2)

# Test for zero-inflation
testZeroInflation(sim_resmacro2)

plotResiduals(sim_resmacro2, form = day_255_epi$salinity_treat)
plotResiduals(sim_resmacro2, form = day_255_epi$temp_treat)



# Pairwise comparisons for salinity × temperature
emmeans(macrosporo_epi_lm, pairwise ~ salinity_treat + temp_treat)




#ANOVA to compare epi cell area betwen treamtens 
macro_treat_anova<-aov(cell_area_um2~treatment_num, data=day_255_epi)
summary(macro_treat_anova)
#p=0.000172
TukeyHSD(macro_treat_anova)

#test anova assumptiosn 
qqnorm(residuals(macro_treat_anova))
qqline(residuals(macro_treat_anova), col = "red")
shapiro.test(residuals(macro_treat_anova))
# p = 5.94e-10 - normality assumption NOT met
plot(macro_treat_anova, which = 1)
leveneTest(cell_area_um2 ~ treatment_num, data = day_255_epi)
#p=0.00025 - equal variance assumption NOT met

#non-parametric test snce anova assumptions violated 
kruskal.test(cell_area_um2 ~ treatment_num, data = day_255_epi)
dunnTest(cell_area_um2 ~ treatment_num, data = day_255_epi, method = "bonferroni")

tapply(day_255_epi$cell_area_um2, day_255_epi$treatment_num, mean)

```

## Visualizations

```{r}
#visulaize mean epidermal cell area by treatment 
epi_d255<- ggplot(data = day_255_epi, aes(x = treatment_num, y = cell_area_um2,
                                          fill = temp_treat)) +
  stat_summary(fun = mean, geom = "col", position = position_dodge(0.8),
               width = 0.7, color = "black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", 
               position = position_dodge(0.8), width = 0.2) +
  labs(x = "Treatment",
    y = expression("Mean Epidermal Cell Area ("*mu*"m"^2*")"),
    fill = "Temperature") +
  ylab(bquote("Mean Epidermal Cell Area  " (μm^2)))+
  scale_fill_manual(values = c("darkgrey","#505050","darkgrey"),
                    labels = c("Ambient","Increased"))+
  scale_x_discrete(labels = c("Amb Salinity\n& Amb Temp",
                              "Increased\nTemp","Decreased\nSalinity"))+
  annotate("text", x=1, y = 0.85, label = "a")+
  annotate("text", x=2, y = 0.75, label = "b")+
  annotate("text", x=3, y = 0.76, label = "ab")+
  my_theme
epi_d255
```

## Calculating estimated marginal means

```{r}
#calculate estimated marginal means based on GLMM
emmeans(macrosporo_epi_lm, pairwise ~ salinity_treat)


emm_mepi_int<-emmeans(macrosporo_epi_lm, ~ salinity_treat * temp_treat, 
                      type = "response")
emm_mepi_int


pairwise_emm_mepi <- contrast(emm_mepi_int, method = "pairwise", 
                              adjust = "tukey")
summary(pairwise_emm_mepi)

# Compact letter display for grouping
cld_letters_mepi <- multcomp::cld(emm_mepi_int, Letters = letters, 
                                adjust = "sidak")
summary(cld_letters_mepi)
cld_letters_mepi

# Convert to dataframe and merge
emmepi_df <- as.data.frame(cld_letters_mepi)
emmepi_df
```

## Visualize EMMs

```{r}
#emms for epidermal cell area between treatments 
epi_emms <- ggplot(emmepi_df, aes(x = salinity_treat, y = response,
                                  fill = temp_treat, group = temp_treat)) +
  geom_bar(stat = "identity", position = position_dodge(0.95)) +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.2, 
                position = position_dodge(0.95)) +
  labs(x = "Salinity Treatment",
    y = expression("Estimated Epidermal Cell Area ("*mu*"m"^2*")"),
    fill = "Temperature") +
  ylab(bquote("Estimated Epidermal Cell Area  " (μm^2)))+
  scale_fill_manual(values=c("darkgrey","#505050"),
                    labels = c("Ambient", "Increased"))+
  scale_x_discrete(labels = c("Ambient", "Decreased"))+
  annotate("text", x=0.76, y = 0.95, label = "a")+
  annotate("text", x=1.24, y = 0.92, label = "ab")+
  annotate("text", x=1.76, y = 0.91, label = "ab")+
  annotate("text", x=2.24, y = 0.85, label = "b")+
  my_theme
epi_emms
```

# Combining All Epidermal Cell Area Plots

```{r}
#combine plots 
# 1. Extract the legend from one of the plots
epi_legend <- get_legend(
  epi_d255 + theme(legend.position = "right"))

# 2. Remove the legends from the three individual plots
p1_epi <- epi_d255 + theme(legend.position = "none",
                             axis.title.y = element_text(size = 11))
p2_epi <- epi_emms + theme(legend.position = "none",
                              axis.title.y = element_text(size = 11))

top_row_epi <- plot_grid(p1_epi, p2_epi, epi_legend, labels = c("A", "B"), ncol = 3)
bottom_row_epi <- plot_grid(epi_legend,
                            label_x = 0, rel_widths = c(1, 1))


epi_plot <- plot_grid(top_row_epi,
                        bottom_row_epi,
                        ncol = 1,
                        rel_heights = c(1, 1))
epi_plot

#saving the figure to the figure_outputs folder 
ggsave("figure6.jpg", plot = epi_plot, width = 6, height = 7, 
       dpi = 300, units = "in",
       path = 'figure_outputs')
```
